import Sidebar from '@/components/layouts/Sidebar'
import { Inter } from 'next/font/google'
import AuthProvider from '@/components/auth/AuthProvider'
import Chat from '@/components/chats/Chat'
import { Toaster } from 'react-hot-toast'
import Header from '@/components/layouts/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Welcome to Untold',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <main className={`${inter.className} min-h-screen h-full flex`}>
      <AuthProvider>
        <Sidebar />
        <section className='p-4 w-full max-h-screen overflow-y-auto'>
          <Header />
          {children}
        </section>
        <Chat />
      </AuthProvider>
    </main>
  )
}
