import Sidebar from '@/components/layouts/Sidebar'
import AuthProvider from '@/components/auth/AuthProvider'
import Chat from '@/components/chats/Chat'
import Header from '@/components/layouts/Header'
import { getServerSession } from 'next-auth'
import authOptions from '../../utils/auth'
import { redirect } from 'next/navigation'

export const metadata = {
  title: 'Welcome to Untold',
  description: 'Generated by create next app'
}

export default async function RootLayout ({ children }) {
  const session = await getServerSession(authOptions)
  if (!session) {
    redirect('/signin')
  }

  return (
    <main className={`min-h-screen h-full flex`}>
      <AuthProvider>
        <Sidebar />
        <section className='p-4 w-full max-h-screen overflow-y-auto'>
          <Header />
          {children}
        </section>
        <Chat />
      </AuthProvider>
    </main>
  )
}
