import Sidebar from '@/components/layouts/Sidebar'
import './globals.css'
import { Inter } from 'next/font/google'
import AuthProvider from '@/components/auth/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Welcome to Untold',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} min-h-screen h-full flex`}>
        <AuthProvider>
          <Sidebar />
          <main className='p-4 w-full'>{children}</main>
        </AuthProvider>
      </body>
    </html>
  )
}
