import { getServerSession } from 'next-auth'
import authOptions from '../../utils/auth'
import { redirect } from 'next/navigation'

export const metadata = {
  title: 'Welcome to Untold',
  description: 'Generated by create next app'
}

export default async function RootLayout ({ children }) {
  const session = await getServerSession(authOptions)
  if (session) {
    redirect('/')
  }

  return <div className='p-4'>{children}</div>
}
